### ISSUE TITLE
purchasePoints

### ISSUE THREAD

**Issue by maxisam** [smile-io/code-samples#18]
In the document, there is a[ way](https://docs.smile.io/docs/points-product#section-purchase-a-pointsproduct-on-behalf-of-a-customer) to purchase points directly. 

However, I can't find the corresponding API. I only see `purchasePointsProduct` under `SweetTooth` object.

Is it possible to have this kinda API?

**Comment by kingscott** [comment]
Hey @maxisam, thanks for stopping by! Sorry for the delayed response. 

There is no way to just purchase points directly. 

The `SweetTooth.purchasePointsProducts()` method would be used when you are buying a PointsProduct (on behalf of a logged in customer), as shown in the documentation you linked. These are rewards that customers can redeem with points they have earned on your store.

What it sounds like you're looking for is our [custom Activity API](https://docs.smile.io/docs/reward-for-any-action). Custom Activities are ways to give a customer points for any action of your choice. 

Let me know if you have any more questions!
